$MODEL PoCat3
# 
# template file: Template.tpl
# ESATAN-TMS 2022, run date 11:02 Mon 7 Apr 2025
# Model name: PoCat3        Analysis case: WCC_Standby_Thermal
#
  $LOCALS
  # GENCODE LOCALS - DO NOT REMOVE 
#
  $NODES
  # GENCODE NODES - DO NOT REMOVE 
#
  $CONDUCTORS
  # GENCODE CONDUCTORS - DO NOT REMOVE 
#
  $CONSTANTS
  # GENCODE CONSTANTS - DO NOT REMOVE 
#
  $ARRAYS
  # GENCODE ARRAYS - DO NOT REMOVE 
#
  $EVENTS
  # GENCODE EVENTS - DO NOT REMOVE 
#
  $SUBROUTINES
  # GENCODE SUBROUTINES - DO NOT REMOVE 
C
  $INITIAL
      GENMOR
  # GENCODE BOUNDARY_CONDS - DO NOT REMOVE 
  # GENCODE INITIAL - DO NOT REMOVE 
C
  $EXECUTION

C
      NLOOP=100
      RELXCA=0.01
      CALL SOLVFM
C
C
      TIMEND=5612.749
      OUTINT=300.0
      NLOOP=100
      RELXCA=0.01
      DTIMEI=100.0
      CALL SOLCYC('SLCRNC',0.01D0,0.01D0,5612.749D0,100,' ','NONE')
C
      CALL SLCRNC
C



  $VARIABLES1
  # GENCODE VARIABLES1 - DO NOT REMOVE 
C
  $VARIABLES2
  # GENCODE VARIABLES2 - DO NOT REMOVE 
C
  $OUTPUTS
      CALL PRNDTB(' ', 'L, T, QS, QE, QA, QI, C', CURRENT)
C
      CALL DMPTMD(' ', 'NODES, CONDUCTORS, CONSTANTS', CURRENT, ' ')




  # GENCODE OUTPUTS - DO NOT REMOVE 
C
$ENDMODEL PoCat3
